from neo4j import GraphDatabase

from closed_agent.settings import settings

STATEMENTS = [
    "CREATE FULLTEXT INDEX entityName IF NOT EXISTS FOR (n:Entity) ON EACH [n.name]",
    """
    MERGE (org:Entity:Organization {name: '当社'})
    MERGE (sales:Entity:Department {name: '営業部'})
    MERGE (hr:Entity:Department {name: '人事部'})
    MERGE (legal:Entity:Department {name: '法務部'})
    MERGE (it:Entity:Department {name: '情報システム部'})
    MERGE (finance:Entity:Department {name: '財務部'})
    MERGE (contracts:Entity:Department {name: '契約管理部'})
    MERGE (credit:Entity:Department {name: '与信室'})
    MERGE (trade:Entity:Department {name: '貿易管理部'})
    MERGE (compliance:Entity:Department {name: 'コンプライアンス室'})
    MERGE (policy:Entity:Policy {name: '情報取扱規程'})
    MERGE (trip:Entity:Procedure {name: '海外出張申請'})
    MERGE (ringi:Entity:Procedure {name: '稟議'})
    MERGE (manual:Entity:Document {name: '出張マニュアル'})
    MERGE (ringi_doc:Entity:Document {name: '稟議運用'})
    MERGE (tacit_ins:Entity:TacitKnowledge {name: '出張保険は契約管理部'})
    MERGE (tacit_large:Entity:TacitKnowledge {name: '大型稟議は財務へ一声'})
    MERGE (tacit_credit:Entity:TacitKnowledge {name: '与信は初回かどうかでルートが変わる'})
    MERGE (skill_trip:Entity:Skill {name: '出張事前チェック'})
    MERGE (skill_ringi:Entity:Skill {name: '稟議ルート判定'})
    MERGE (skill_contract:Entity:Skill {name: '契約レビュー依頼'})
    MERGE (invest:Entity:Procedure {name: '事業投資'})
    MERGE (lesson:Entity:TacitKnowledge {name: '投資の失敗は論点漏れ'})
    MERGE (skill_invest:Entity:Skill {name: '事業投資の申請チェック'})
    MERGE (skill_credit:Entity:Skill {name: '与信チェック'})
    MERGE (skill_trade:Entity:Skill {name: '貿易書類チェック'})
    MERGE (skill_comp:Entity:Skill {name: 'コンプラ事前確認'})
    MERGE (shipping:Entity:Procedure {name: '船積'})
    MERGE (tacit_trade:Entity:TacitKnowledge {name: '貿易書類は通貨と建値を先に見る'})
    MERGE (tacit_comp:Entity:TacitKnowledge {name: '該非判定書は再輸出先に渡さない'})
    MERGE (org)-[:HAS_DEPARTMENT]->(sales)
    MERGE (org)-[:HAS_DEPARTMENT]->(hr)
    MERGE (org)-[:HAS_DEPARTMENT]->(legal)
    MERGE (org)-[:HAS_DEPARTMENT]->(it)
    MERGE (org)-[:HAS_DEPARTMENT]->(finance)
    MERGE (org)-[:HAS_DEPARTMENT]->(contracts)
    MERGE (org)-[:HAS_DEPARTMENT]->(credit)
    MERGE (org)-[:HAS_DEPARTMENT]->(trade)
    MERGE (org)-[:HAS_DEPARTMENT]->(compliance)
    MERGE (policy)-[:GOVERNS]->(trip)
    MERGE (policy)-[:GOVERNS]->(ringi)
    MERGE (hr)-[:OWNS]->(trip)
    MERGE (legal)-[:OWNS]->(policy)
    MERGE (contracts)-[:KNOWS]->(tacit_ins)
    MERGE (tacit_ins)-[:NOT_IN_MANUAL]->(manual)
    MERGE (tacit_ins)-[:ABOUT]->(trip)
    MERGE (skill_trip)-[:ENCODES]->(tacit_ins)
    MERGE (sales)-[:KNOWS]->(tacit_large)
    MERGE (tacit_large)-[:ABOUT]->(ringi)
    MERGE (skill_ringi)-[:ENCODES]->(tacit_large)
    MERGE (credit)-[:KNOWS]->(tacit_credit)
    MERGE (tacit_credit)-[:ABOUT]->(ringi)
    MERGE (skill_ringi)-[:ENCODES]->(tacit_credit)
    MERGE (legal)-[:USES]->(skill_contract)
    MERGE (it)-[:OPERATES]->(trip)
    MERGE (finance)-[:OWNS]->(invest)
    MERGE (lesson)-[:ABOUT]->(invest)
    MERGE (skill_invest)-[:ENCODES]->(lesson)
    MERGE (skill_invest)-[:USES]->(tacit_credit)
    MERGE (credit)-[:USES]->(skill_credit)
    MERGE (skill_credit)-[:ENCODES]->(tacit_credit)
    MERGE (trade)-[:OWNS]->(shipping)
    MERGE (trade)-[:KNOWS]->(tacit_trade)
    MERGE (tacit_trade)-[:ABOUT]->(shipping)
    MERGE (skill_trade)-[:ENCODES]->(tacit_trade)
    MERGE (compliance)-[:KNOWS]->(tacit_comp)
    MERGE (skill_comp)-[:ENCODES]->(tacit_comp)
    MERGE (policy)-[:GOVERNS]->(shipping)
    """,
]


def seed() -> None:
    driver = GraphDatabase.driver(settings.neo4j_uri, auth=(settings.neo4j_user, settings.neo4j_password))
    with driver.session() as session:
        for statement in STATEMENTS:
            session.run(statement)
    driver.close()


if __name__ == "__main__":
    seed()
    print("seeded graph")
